fix: true
ignores:
  - ".github/**"
  - ".mypy_cache/**"
  - ".pytest_cache/**"
  - "migrations/**"
noInlineConfig: true
noProgress: true
config:
  default: true
  MD013:
    line_length: 120
  MD040: false
