exclude: >
  (?x)^(
    venv/.* |
    migrations/.* |
    prephouse_pb2.py |
    prephouse_pb2_grpc.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-implicit-str-concat
          - flake8-print
          - flake8-return
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --follow-imports=silent]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      -   id: blacken-docs
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
