version: '3'
services:
  database:
    container_name: prephouse-db
    image: postgres
    environment:
      - POSTGRES_DB=prephouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  migration:
    container_name: prephouse-migration
    image: prephouse-backend
    build: .
    command: flask db upgrade
    volumes:
      - './:/app'
    env_file:
      - .env.development
      - .env
    links:
      - database
    depends_on:
      - database
  prephouse:
    container_name: prephouse-backend
    image: prephouse-backend
    build: ./
    ports:
      - '3001:5000'
    volumes:
      - './:/app'
    env_file:
      - .env.development
      - .env
    links:
      - database
    depends_on:
      - migration
networks:
  default:
    external: true
    name: prephouse
