[tool.black]
line-length = 100
exclude = '''
/(
    \.git
  | \.github
  | \.sh
  | \.venv
  | Dockerfile
  | prephouse/prephouse_pb2.py
  | prephouse/prephouse_pb2_grpc.py
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
