"""add overall score

Revision ID: 09a585955767
Revises: fa9e5fe74b8e
Create Date: 2022-02-05 16:13:33.721221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a585955767'
down_revision = 'fa9e5fe74b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'score')
    # ### end Alembic commands ###
