"""fix uid

Revision ID: 350679be47ce
Revises: 457a6bd40ecb
Create Date: 2022-02-19 22:35:52.692218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '350679be47ce'
down_revision = '457a6bd40ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name="upload_user_id_fkey", table_name="upload", type_="foreignkey")
    op.alter_column('user', 'id',
                    existing_type=postgresql.UUID(),
                    type_=sa.String(),
                    existing_nullable=False,
                    autoincrement=False)
    op.alter_column('upload', 'user_id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(
        constraint_name="upload_user_id_fkey",
        source_table="upload",
        referent_table="user",
        local_cols=["user_id"],
        remote_cols=["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'user_id',
                    existing_type=sa.String(),
                    type_=postgresql.UUID(),
                    existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
