"""add cloudfront

Revision ID: 57f17233f3e1
Revises: d785cb47270b
Create Date: 2022-02-09 02:35:47.251151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57f17233f3e1'
down_revision = 'd785cb47270b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filler_word')
    op.add_column('upload_question', sa.Column('cloudfront_url', sa.Text(), nullable=True))
    op.add_column('upload_question', sa.Column('manifest_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_question', 'manifest_file')
    op.drop_column('upload_question', 'cloudfront_url')
    op.create_table('filler_word',
    sa.Column('upload_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='filler_word_upload_id_fkey'),
    sa.PrimaryKeyConstraint('upload_id', 'word', name='filler_word_pkey')
    )
    # ### end Alembic commands ###
