"""add overall score

Revision ID: 58adf3117261
Revises: fa9e5fe74b8e
Create Date: 2022-02-04 14:58:42.905364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58adf3117261'
down_revision = 'fa9e5fe74b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'score')
    # ### end Alembic commands ###
