"""added textual summary

Revision ID: c769c03bb69f
Revises: e862a2efee6d
Create Date: 2022-03-10 02:56:46.149128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c769c03bb69f'
down_revision = 'e862a2efee6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_question', sa.Column('textual_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_question', 'textual_summary')
    # ### end Alembic commands ###
