"""practice_session_constraints

Revision ID: e862a2efee6d
Revises: 62c760d44d7e
Create Date: 2022-03-09 19:09:13.898109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e862a2efee6d'
down_revision = '62c760d44d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_question', 'upload_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_question', 'upload_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
