"""add col to uplaod table

Revision ID: f5611b723675
Revises: fa9e5fe74b8e
Create Date: 2022-02-06 05:32:34.646100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5611b723675'
down_revision = 'fa9e5fe74b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('cloudfront_url', sa.Text(), nullable=True))
    op.add_column('upload', sa.Column('manifest_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'manifest_file')
    op.drop_column('upload', 'cloudfront_url')
    # ### end Alembic commands ###
