"""add overall score

Revision ID: f97715273f19
Revises: 58adf3117261
Create Date: 2022-02-04 15:12:03.581378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97715273f19'
down_revision = '58adf3117261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'score')
    # ### end Alembic commands ###
