name: deployment
on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docker container in Elastic Beanstalk
        run: deploy.sh
        shell: bash
      - name: Notify deployment of production to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        with:
          environment: 'production'
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}
