# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prephouse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
    name='prephouse.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0fprephouse.proto\"\x15\n\x05Video\x12\x0c\n\x04link\x18\x01 \x01(\t\"\x9f\x02\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12#\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\x11.Feedback.Feature\x12\x14\n\x07\x63omment\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x17\n\nconfidence\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\ttimeStart\x18\x05 \x01(\x02H\x02\x88\x01\x01\x12\x14\n\x07timeEnd\x18\x06 \x01(\x02H\x03\x88\x01\x01\"M\n\x07\x46\x65\x61ture\x12\t\n\x05PAUSE\x10\x00\x12\n\n\x06VOLUME\x10\x01\x12\t\n\x05LIGHT\x10\x02\x12\x08\n\x04GAZE\x10\x03\x12\x0b\n\x07\x45MOTION\x10\x04\x12\t\n\x05PITCH\x10\x05\x42\n\n\x08_commentB\r\n\x0b_confidenceB\x0c\n\n_timeStartB\n\n\x08_timeEnd\"+\n\x0c\x46\x65\x65\x64\x62\x61\x63kList\x12\x1b\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x03(\x0b\x32\t.Feedback29\n\x0fPrephouseEngine\x12&\n\x0bGetFeedback\x12\x06.Video\x1a\r.FeedbackList\"\x00\x62\x06proto3'
)



_FEEDBACK_FEATURE = _descriptor.EnumDescriptor(
    name='Feature',
    full_name='Feedback.Feature',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='PAUSE', index=0, number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='VOLUME', index=1, number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='LIGHT', index=2, number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='GAZE', index=3, number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='EMOTION', index=4, number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='PITCH', index=5, number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=200,
    serialized_end=277,
)
_sym_db.RegisterEnumDescriptor(_FEEDBACK_FEATURE)


_VIDEO = _descriptor.Descriptor(
    name='Video',
    full_name='Video',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='link', full_name='Video.link', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=19,
    serialized_end=40,
)


_FEEDBACK = _descriptor.Descriptor(
    name='Feedback',
    full_name='Feedback',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='category', full_name='Feedback.category', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='comment', full_name='Feedback.comment', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='score', full_name='Feedback.score', index=2,
            number=3, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='confidence', full_name='Feedback.confidence', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='timeStart', full_name='Feedback.timeStart', index=4,
            number=5, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='timeEnd', full_name='Feedback.timeEnd', index=5,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _FEEDBACK_FEATURE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='_comment', full_name='Feedback._comment',
            index=0, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
        _descriptor.OneofDescriptor(
            name='_confidence', full_name='Feedback._confidence',
            index=1, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
        _descriptor.OneofDescriptor(
            name='_timeStart', full_name='Feedback._timeStart',
            index=2, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
        _descriptor.OneofDescriptor(
            name='_timeEnd', full_name='Feedback._timeEnd',
            index=3, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
    ],
    serialized_start=43,
    serialized_end=330,
)


_FEEDBACKLIST = _descriptor.Descriptor(
    name='FeedbackList',
    full_name='FeedbackList',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='feedback', full_name='FeedbackList.feedback', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=332,
    serialized_end=375,
)

_FEEDBACK.fields_by_name['category'].enum_type = _FEEDBACK_FEATURE
_FEEDBACK_FEATURE.containing_type = _FEEDBACK
_FEEDBACK.oneofs_by_name['_comment'].fields.append(
    _FEEDBACK.fields_by_name['comment'])
_FEEDBACK.fields_by_name['comment'].containing_oneof = _FEEDBACK.oneofs_by_name['_comment']
_FEEDBACK.oneofs_by_name['_confidence'].fields.append(
    _FEEDBACK.fields_by_name['confidence'])
_FEEDBACK.fields_by_name['confidence'].containing_oneof = _FEEDBACK.oneofs_by_name['_confidence']
_FEEDBACK.oneofs_by_name['_timeStart'].fields.append(
    _FEEDBACK.fields_by_name['timeStart'])
_FEEDBACK.fields_by_name['timeStart'].containing_oneof = _FEEDBACK.oneofs_by_name['_timeStart']
_FEEDBACK.oneofs_by_name['_timeEnd'].fields.append(
    _FEEDBACK.fields_by_name['timeEnd'])
_FEEDBACK.fields_by_name['timeEnd'].containing_oneof = _FEEDBACK.oneofs_by_name['_timeEnd']
_FEEDBACKLIST.fields_by_name['feedback'].message_type = _FEEDBACK
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.message_types_by_name['FeedbackList'] = _FEEDBACKLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
    'DESCRIPTOR' : _VIDEO,
    '__module__' : 'prephouse_pb2'
    # @@protoc_insertion_point(class_scope:Video)
})
_sym_db.RegisterMessage(Video)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
    'DESCRIPTOR' : _FEEDBACK,
    '__module__' : 'prephouse_pb2'
    # @@protoc_insertion_point(class_scope:Feedback)
})
_sym_db.RegisterMessage(Feedback)

FeedbackList = _reflection.GeneratedProtocolMessageType('FeedbackList', (_message.Message,), {
    'DESCRIPTOR' : _FEEDBACKLIST,
    '__module__' : 'prephouse_pb2'
    # @@protoc_insertion_point(class_scope:FeedbackList)
})
_sym_db.RegisterMessage(FeedbackList)



_PREPHOUSEENGINE = _descriptor.ServiceDescriptor(
    name='PrephouseEngine',
    full_name='PrephouseEngine',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=377,
    serialized_end=434,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetFeedback',
            full_name='PrephouseEngine.GetFeedback',
            index=0,
            containing_service=None,
            input_type=_VIDEO,
            output_type=_FEEDBACKLIST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_PREPHOUSEENGINE)

DESCRIPTOR.services_by_name['PrephouseEngine'] = _PREPHOUSEENGINE

# @@protoc_insertion_point(module_scope)
